# Setting up persistent storage for different components of the setup. Ensures data remains available
# between container restarts.
volumes:
  backend_venv:
    driver: local
  frontend_node_modules: 
    driver: local

services:
  redis:
    image: redis:latest
    ports:
      - "6379:6379"     
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5 

  backend:
    image: n9neiiv3s/cifar-10-cnn-backend:latest
    user: nonrootuser
    # volumes:
    #   - ./backend:/backend
    #   - /backend/venv
    #   - backend_venv:/backend/venv
    ports:
      - "5000:5000"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    depends_on:
      redis:
        condition: service_healthy
    stop_grace_period: 10s
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    healthcheck:
      test: curl -f http://localhost:5000/health || exit 1
      interval: 10s
      timeout: 5s
      retries: 5


  celery_worker:
    image: n9neiiv3s/cifar-10-cnn-backend:latest
    # volumes:
    #   - ./backend:/backend
    #   - /backend/venv
    #   - backend_venv:/backend/venv
    command: /backend/venv/bin/celery -A worker worker --loglevel=info
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    depends_on:
      redis:
        condition: service_healthy
      backend:
        condition: service_healthy
    stop_grace_period: 10s
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"


  frontend:
    user: node
    image: n9neiiv3s/cifar-10-cnn-frontend:latest
    # volumes:
    #   - ./frontend:/frontend
    #   - /frontend/node_modules
    #   # - /frontend/vite.config.js
    #   - frontend_node_modules:/frontend/node_modules
    ports:
      - "5173:5173"
    depends_on:
      backend:
        condition: service_healthy
    stop_grace_period: 10s

networks:
  elk:
    driver: bridge