services:
  backend:
    build: ./backend
    ports:
      - "5000:5000"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    environment:
    - NVIDIA_VISIBLE_DEVICES=all
    - FLASK_ENV=development
  frontend:
    build: ./frontend
    ports:
      - "80:80"